### ISSUE TITLE
Missing operation summary fails CI; fixing it triggers "invalid operation ID" (catch-22)

### ISSUE THREAD

**Issue by cmars** [snyk/sweater-comb#137]
When introducing Optic CI into an existing project, in addition to #136 I found these failures:

```
  FAIL   This Specification
  x this specification:  must have an org or group tenant
    expected support for org or group tenant: expected [] to have a length above 0 but got 0
    Read more in our API guide (​https://github.com/snyk/sweater-comb/blob/main/docs/standards.md#organization-and-group-tenants-for-resources​)
    at (/Users/cmars/Projects/registry/src/web/routes/api/v3/resources/_examples/hello_world/2021-06-13/spec.yaml:1:0)


  FAIL  GET /examples/hello_world/{id}
  x requirement for operation: GET /examples/hello_world/{id} must have a summary
    expected undefined to exist
    Read more in our API guide (​https://github.com/snyk/sweater-comb/blob/main/docs/standards.md#operation-summary​)
    at (/Users/cmars/Projects/registry/src/web/routes/api/v3/resources/_examples/hello_world/2021-06-13/spec.yaml:65:2767)


  FAIL  POST /examples/hello_world
  x requirement for operation: POST /examples/hello_world must have a summary
    expected undefined to exist
    Read more in our API guide (​https://github.com/snyk/sweater-comb/blob/main/docs/standards.md#operation-summary​)
    at (/Users/cmars/Projects/registry/src/web/routes/api/v3/resources/_examples/hello_world/2021-06-13/spec.yaml:14:250)
```

Oh, easy fix, I thought, I'll go and add summaries to those operations, it's a non-breaking change, and we'll be good!

Well, no, when I added the summaries, it triggered this rule failure because the operation IDs are also non-standard:

```
  FAIL  GET /examples/hello_world/{id}
  x updated operation: GET /examples/hello_world/{id} must have the correct operationId format
    operationId "helloWorldGetOne" must be camelCase (helloWorldGetOne) and start with get|create|list|update|delete: expected false to be truthy
    Read more in our API guide (​https://github.com/snyk/sweater-comb/blob/main/docs/standards.md#operation-ids​)
    at (/Users/cmars/Projects/registry/src/web/routes/api/v3/resources/_examples/hello_world/2021-06-13/spec.yaml:66:2834)


  FAIL  POST /examples/hello_world
  x updated operation: POST /examples/hello_world must have the correct operationId format
    operationId "helloWorldCreate" must be camelCase (helloWorldCreate) and start with get|create|list|update|delete: expected false to be truthy
    Read more in our API guide (​https://github.com/snyk/sweater-comb/blob/main/docs/standards.md#operation-ids​)
    at (/Users/cmars/Projects/registry/src/web/routes/api/v3/resources/_examples/hello_world/2021-06-13/spec.yaml:14:250)
```

And I can't fix _those_ without a breaking change. Even if I introduce a new release version that fixes this, I'm still not going to be able to get these existing operations to pass CI.

**Comment by acunniffe** [comment]
The catch-22s are my biggest fear for using `optic-ci` at scale and part of the reason why measuring it with analytics is going to really help us spot these sort of things early. The more rules we add, the more interactions between them we need to be conscious of. Let's take naming rules, the reason they only apply on `added` is because if they also applied on `change` or as a `requirement` -- the only way to fix the name would be a breaking change (to the API consumers renaming looks like adding a new property, and removing another one). 

I feel much more confident the rules won't interact in strange ways for very material *breaking change rules we built together since we were thinking about this the whole time. 

I'm less confident we found all the catch-22s in the metadata rules. I'm opening a PR here that fixes this one class of interaction. https://github.com/snyk/sweater-comb/pull/139

Longer term, I think your `effectiveOn` idea is really the direction we should be going, less all these rules become very hard to read and reason about https://github.com/snyk/sweater-comb/issues/136

**Comment by acunniffe** [comment]
Another possibility that just occurred to me is adding a qualifier to the `operations.changed` rule syntax 

`operations.changed.attribute('operationId').must`

so it only triggers when that attribute changes, not the entire operation. Probably more akin to what we would want for metadata rules.

**Comment by cmars** [comment]
I think the catch-22 is avoided by #140 paired with an `effectiveUntil`. With the capability for time-windowed rules, we can tailor rules to fit any past releases as needed to avoid stubbing our toes on nasty surprises during non-breaking maintenance on them. Conversely we can also let the rules fail any change to an old release, and use that as a motivator for a new release that meets standards.
